# SPDX-FileCopyrightText: 2024 Simon Dalvai <info@simondalvai.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Pocket Broomball"
SPDX-PackageSupplier = "Simon Dalvai <info@simondalvai.org>"
SPDX-PackageDownloadLocation = "https://github.com/dulvui/pocket-broomball"

[[annotations]]
path = "game/src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "metadata/**",
    "fdroid/**",
    "version",
    "flatpak/org.simondalvai.pocket-broomball.appdata.xml",
    "flatpak/org.simondalvai.pocket-broomball.desktop"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "game/assets/locker/**",
    "game/assets/shop/**",
    "game/assets/animated-player/**",
    "game/assets/progressbar**",
    "game/assets/ball.png",
    "game/assets/field.png",
    "game/assets/corner.png",
    "game/assets/goal.png",
    "game/assets/pause.png",
    "game/assets/broomballcoin.png",
    "game/assets/gamebreak.png",
    "exportOptions.plist",
    "game/export_presets.**"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "game/translations/**",
    "game/assets/theme/**",
    "README.md",
    "**.import",
    "game/project.godot",
    "game/default_bus_layout.tres",
    ".gitignore"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Simon Dalvai <info@simondalvai.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "game/icon.png",
    "game/AppIcons/**",
    "flatpak/icon-256.png"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Broomball icon created by Freepik - https://flaticon.com"
SPDX-License-Identifier = "Flaticon License"

[[annotations]]
path = [
    "game/assets/sounds/commentator/**",
    "game/assets/sounds/click.ogg",
    "game/assets/leaderboardsComplex.png",
    "game/assets/video.png",
    "game/assets/sounds/click.ogg",
    "game/assets/next.png",
    "game/assets/prev.png"
    ]
precedence = "aggregate"
SPDX-FileCopyrightText = "2010 - 2022 https://kenney.nl"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/snowflake.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 mkwong98 https://opengameart.org/content/snow-flake"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/sounds/chill-music.ogg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 furbyguy https://freesound.org/people/furbyguy/sounds/365187/"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/sounds/music.ogg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 furbyguy https://freesound.org/people/furbyguy/sounds/388101/"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/sounds/croud.ogg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 giddster https://freesound.org/people/giddster/sounds/406214/"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/sounds/horn.ogg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 santino_c https://freesound.org/people/santino_c/sounds/170825/"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/sounds/hit.ogg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 volivieri https://freesound.org/people/volivieri/sounds/37155/"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "game/assets/font/Carlito-Regular.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Łukasz Dziedzic https://www.1001fonts.com/carlito-font.html"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "game/assets/font/DSEG7ClassicMini-Bold.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Keshikan https://github.com/keshikan/DSEG"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["game/assets/link-buttons/codeberg.svg", "game/assets/link-buttons/mastodon.svg", "game/assets/link-buttons/github.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "simple-icons https://github.com/simple-icons/simple-icons"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "game/assets/teams/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 The corresponding team organization"
SPDX-License-Identifier = "No license defined"

[[annotations]]
path = "game/assets/broomballcentral**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 https://broomballcentral.com"
SPDX-License-Identifier = "No license defined"
